[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "1"
members = [
  "protocol/rtmp",
  "library/bytesio",
  "library/container/flv",
  "library/container/mpegts",
  "library/codec/h264",
  "library/logger",
  "library/streamhub",
  "library/common",
  "library/ffmpeg",
  "protocol/tcp",
  "tcp_test/server",
  "tcp_test/client",
  "tcp_test/protocol",
  "tcp_test/client",

]

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.0", features = ["macros", "rt-multi-thread"] }
