[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "1"
members = [

  "tcp_test/protocol",
  "tcp_test/client",
  "tcp_test/server",
  "surreal_db",
  "ctls",

]
#i know it's just for a commit not cuz i wanted it