[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = "debuginfo"

[profile.client]
inherits = "release"
opt-level = "s"

[workspace]
resolver = "1"
members = [
  "lib_start",
  "protocol/tcp",
  "common_lib",
  "protocol/multicast",
  "lib_db",
]

[dependencies]
tcp = { path = "./protocol/tcp/" }
rpassword = "7.3.1"
lib_start = { path = "./lib_start" }
tokio = "1.40.0"

#
# #i know it's just for a commit not cuz i wanted it
