[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "1"
members = [
  "lib_start",
  "protocol/tcp",
  "common_lib",
  "protocol/multicast",
  "lib_db",
]

[dependencies]
# sdwd = "1.0.0"
tcp = { path = "./protocol/tcp/" }
rpassword = "7.3.1"
lib_start = { path = "./lib_start" }
tokio = "1.40.0"

#
# #i know it's just for a commit not cuz i wanted it
