[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = "debuginfo"

[profile.client]
inherits = "release"
opt-level = "s"

[workspace]
resolver = "1"
members = [
  "common_lib",
  "lib_db", "lib_start", "tcp",
]

[dependencies]
rpassword = "7.3.1"
tokio = "1.40.0"

#
# #i know it's just for a commit not cuz i wanted it
