[package]
name = "Connie"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "1"
members = [

  "tcp_test/protocol",
  "tcp_test/client",
  "tcp_test/server",
  "surreal_db", "start",

]

[dependencies]
local-ip-address = "0.6.2"
rcgen = "0.13.1"


#i know it's just for a commit not cuz i wanted it