[package]
name = "surreal_db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
surrealdb = { version = "2.0.3", features = ["kv-rocksdb"] }
tokio = "1.39.2"
once_cell = "1.19.0"
log = "0.4.22"
uuid = "1.10.0"
lazy_static = "1.5.0"
directories = "5.0.1"
