#!/usr/bin/env bash
bin_dir=`dirname "$0"`
if [ "$1" != "-cc1" ]; then
    "$bin_dir/clang" --target=aarch64-linux-android33 "$@"
else
    # Target is already an argument.
    "$bin_dir/clang" "$@"
fi
