[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.40.0"
multicast = { path = "../multicast/" }
common_lib = { path = "../../common_lib/" }
lib_start = { path = "../../lib_start/" }
lib_db = { path = "../../lib_db/" }
log = "0.4.22"
