[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23.16"
tokio = "1.41.0"
multicast = { path = "../multicast/" }
common_lib = { path = "../../common_lib/" }
lib_start = { path = "../../lib_start/" }
log = "0.4.22"
rcgen = "=0.13.1"
webpki-roots = "0.26.7"
