[package]
name = "lib_start"
version = "0.1.0"
edition = "2021"


[dependencies]
common_lib = { path = "../common_lib/" }
multicast = { path = "../protocol/multicast/" }
lib_db = { path = "../lib_db/" }
sysinfo = "0.32.0"
log = "0.4.22"
rpassword = "7.3.1"
num_cpus = "1.16.0"
tokio = "1.40.0"
