[package]
name = "data_base"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7.12"
serde = "1.0.204"
tokio = "1.39.2"
log = "0.4.22"
lazy_static = "1.5.0"
directories = "5.0.1"
