[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["macros", "net", "rt-multi-thread"] }
serde = "1.0.217"
common_lib = { path = "../common_lib/"}
lib_db = {path = "../lib_db/"}
tokio-rustls = "0.26.1"
