name: Rust
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly 
      fail-fast: false
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_CLUSTER}}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain}}
      - name: Build
        run: cargo build --verbose
      
